const projectData = [
  {
    banner: "https://i.ibb.co/wWXdX66/Alumni.png",
    title: "Masai Alumni Website",
    desc: "Welcome to our alumni website! It's a place where people who graduated from our school or program can connect and help each other out. We have two main goals helping current students find jobs and supporting our alumni even after they have already landed a job.",
    tech_stack: [
      "React",
      "React-Router",
      "React-Redux",
      "React-thunk",
      "TypeScript",
      "NodeJS",
      "ExpressJS",
      "MySql",
      "JavaScript",
      "Chakra-UI",
    ],
    work_type: "A group project.",
    github: "",
    demo: "https://masai-alumni-temp.onrender.com/",
    type: "MERN",
  },
  {
    banner: "https://i.ibb.co/fFNF9zC/quize.png",
    title: "Quize App",
    desc: "This is Quize App which you can use for play or solve quize on various subject. I have used opentdb API.",
    tech_stack: [
      "React",
      "React-Router",
      "React-Redux",
      "React-thunk",
      "JavaScript",
      "Chakra-UI",
    ],
    work_type: "An Individual Project.",
    github: "https://github.com/shivamkumar24/Quiz-App",
    demo: "https://quiz-app-9jll.vercel.app/",
    type: "React",
  },
  {
    banner: "https://i.ibb.co/Hd5BFxw/Weather-App.png",
    title: "Weather App",
    desc: "This is Weather App which help you to know about particular place temperature and weather.",
    tech_stack: ["React", "JavaScript", "CSS"],
    work_type: "An Individual Project.",
    github: "https://github.com/shivamkumar24/Weather-App",
    demo: "https://weather-app-sage-nu-80.vercel.app/",
    type: "React",
  },
  {
    banner: "outfitstore.jpeg",
    title: "OutfitStore.com",
    desc: "The outfit is a MERN Stack web application & is a clone of lifestylestore.com. With a vast collection of fashion and clothing products, we offer a seamless shopping experience. Our user-friendly interface ensures a hassle-free shopping experience.",
    tech_stack: [
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "JWT-Authentication",
      "Bcrypt",
      "React",
      "React-Router",
      "Chakra-UI",
      "JavaScript",
    ],
    work_type: "An Individual Project.",
    github: "https://github.com/shivamkumar24/Lifestylestores.com-Clone",
    demo: "https://outfitstore-eta.vercel.app/",
    type: "MERN",
  },
  {
    banner: "doorstep.jpeg",
    title: "DoorStep.com",
    desc: "DoorStep.com is clone of nearbuy.com MERN Stack web application that allows you to buy voucher and coupons. It has a variety of categories, just visit the product listing page and you will see all the services near your location.",
    tech_stack: [
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "JWT-Authentication",
      "Bcrypt",
      "React",
      "React-Router",
      "React-Redux",
      "React-thunk",
      "Chakra-UI",
    ],
    work_type: "A group project executed in 5 days.",
    github: "https://github.com/KaustubhN12/dizzy-stitch-9009",
    demo: "https://doorstep-iota.vercel.app/",
    type: "MERN",
  },
  {
    banner: "fitfactory.jpeg",
    title: "Fit-Factory.com",
    desc: "Fit-Factory is clone of HealthKart. This is generally based on products which is related to our health and it is that website where we sell product direct to customer.",
    tech_stack: [
      "React",
      "React-Router",
      "React-Redux",
      "React-thunk",
      "JSON",
      "Chakra-UI",
    ],
    work_type: "A group project executed in 4 days.",
    github: "https://github.com/Sachin-Kesarwani/detailed-hour-2985/",
    demo: "https://fit-factory.vercel.app/",
    type: "React",
  },
  {
    banner: "trademart.jpeg",
    title: "TradeMart.com",
    desc: "TradeMart is clone website of IndiaMart. IndiaMart Indian e-commerce company that provides B2B and customer to customer sales services via its web portal.",
    tech_stack: [
      "React",
      "React-Router",
      "React-Redux",
      "React-thunk",
      "Firebase",
      "JSON",
    ],
    work_type: "A group project executed in 5 days.",
    github: "https://github.com/jithstephen13/TradeMart",
    demo: "https://trademart.netlify.app/",
    type: "React",
  },
  {
    banner: "notebook.jpeg",
    title: "NoteBook",
    desc: "NoteBook is a notes application. That is maintain your daily life note. it works like sticky note. You can do add, delete, and update your note.",
    tech_stack: ["React", "React-Router", "React-Redux", "React-thunk", "JSON"],
    work_type: "An Individual Project.",
    github: "https://github.com/shivamkumar24/NoteBook",
    demo: "https://note-book-beta.vercel.app/",
    type: "React",
  },
  {
    banner: "beautybebo.jpeg",
    title: "Beautybebo.com - Clone",
    desc: "Beauty Bebo is India's fastest-growing online retail store for makeup, skin care, hair care, personal care, mom and baby care, fragrance, and Ayurveda products.",
    tech_stack: ["React", "React-Router", "API", "JavaScript", "ES6"],
    work_type: "An individual project executed in 4 days.",
    github: "https://github.com/shivamkumar24/Beautybebo.com-Clone",
    demo: "https://beautybebo-com-clone-jdmb.vercel.app/",
    type: "React",
  },
  {
    banner: "sugarcosmetics.jpeg",
    title: "SugarCosmetics.com - Clone",
    desc: "Sugar Cosmetics is one of India's fastest-growing premium cosmetic companies. it has become the first choice of many Indian women.",
    tech_stack: ["JavaScript", "ES6", "Local Storage", "CSS", "HTML"],
    work_type: "An individual project executed in 4 days.",
    github: "https://github.com/shivamkumar24/SugarCosmetics.com-Clone",
    demo: "https://effortless-strudel-bc1dac.netlify.app/",
    type: "JavaScript",
  },
  {
    banner: "myntra.jpeg",
    title: "Myntra.com - Clone",
    desc: "Myntra is a one stop shop for all your fashion and lifestyle needs. Being India's largest e-commerce store for fashion and lifestyle products.",
    tech_stack: ["JavaScript", "ES6", "Local Storage", "CSS", "HTML"],
    work_type: "A group project executed in 4 days.",
    github: "https://github.com/shivamkumar24/Myntra_Clone",
    demo: "https://idyllic-begonia-67c760.netlify.app/",
    type: "JavaScript",
  },
];

export default projectData;
